services:
  - type: web
    name: pokedex
    runtime: node
    rootDir: .  
    buildCommand: npm install
    startCommand: node pokedexServer.js
    envVars:
      - key: MONGO_CONNECTION_STRING
        value: mongodb+srv://akhilgunda:LBJ@cluster0.4zgarst.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGO_DB_NAME
        value: CMSC335DB
      - key: MONGO_COLLECTION
        value: campApplicants
    plan: free
